OBJECT_ADDED = "OBJECT_ADDED"
OBJECT_REMOVED = "OBJECT_REMOVED"
OBJECT_UPDATED = "OBJECT_UPDATED"

SELECTION_CHANGED = "SELECTION_CHANGED"
VISIBILITY_CHANGED = "VISIBILITY_CHANGED"

INTERACTION_MODE_CHANGED = "INTERACTION_MODE_CHANGED"

REGISTRATION_IMPORT_REQUESTED = "REGISTRATION_IMPORT_REQUESTED"
REGISTRATION_POINT_SIZE_CHANGED = "REGISTRATION_POINT_SIZE_CHANGED"
REGISTRATION_DELETE_LAST_MARKER = "REGISTRATION_DELETE_LAST_MARKER"
REGISTRATION_RESET_LAYOUT = "REGISTRATION_RESET_LAYOUT"