from typing import Protocol, runtime_checkable, Dict
from PySide6 import QtWidgets

@runtime_checkable
class IModule(Protocol):
    def get_main_widget(self) -> QtWidgets.QWidget: ...
    def get_toolboxes(self) -> Dict[str, QtWidgets.QWidget]: ...
    def cleanup(self) -> None: ...

@runtime_checkable
class IWorkspaceTab(Protocol):
    def get_widget(self) -> QtWidgets.QWidget: ...
    def get_title(self) -> str: ...