# core/scene/events/scene_events.py

class SceneEvents:
    """Eventos gerais de gerenciamento da cena."""
    OBJECT_ADDED = "OBJECT_ADDED"
    OBJECT_REMOVED = "OBJECT_REMOVED"
    OBJECT_UPDATED = "OBJECT_UPDATED"
    SELECTION_CHANGED = "SELECTION_CHANGED"
    VISIBILITY_CHANGED = "VISIBILITY_CHANGED"
    INTERACTION_MODE_CHANGED = "INTERACTION_MODE_CHANGED"
    LAYOUT_CHANGED = "LAYOUT_CHANGED"


class VolumeEvents:
    """Eventos específicos para manipulação de volumes e DICOM."""
    DICOM_LOADED = "DICOM_LOADED"
    VOLUME_MODIFIED = "VOLUME_MODIFIED"
    WINDOW_LEVEL_CHANGED = "WINDOW_LEVEL_CHANGED"


class RegistrationEvents:
    """Eventos específicos para ferramentas de registro."""
    IMPORT_REQUESTED = "REGISTRATION_IMPORT_REQUESTED"
    POINT_ADDED = "REGISTRATION_POINT_ADDED"
    POINT_SIZE_CHANGED = "REGISTRATION_POINT_SIZE_CHANGED"
    DELETE_LAST_MARKER = "REGISTRATION_DELETE_LAST_MARKER"
    RESET_LAYOUT = "REGISTRATION_RESET_LAYOUT"
    ALIGNMENT_REQUESTED = "REGISTRATION_ALIGNMENT_REQUESTED"
    CLEAR_POINTS = "REGISTRATION_CLEAR_POINTS"
    TARGET_CHANGED = "REGISTRATION_TARGET_CHANGED"
    SOURCE_CHANGED = "REGISTRATION_SOURCE_CHANGED"